### ISSUE TITLE
Final Code Submission Milestone (Checklist)

### ISSUE THREAD

**Issue by landenf** [landenf/Software-Engineering-IV-Game#104]
Ensure your code is cleaned up:

Todo:

- [x] Class or method stubs
- [x] Dead or unused code
- [x] Temporary or internal comments
- [x] The code base should be well organized and demonstrate software engineering principles to support its maintainability
- [x] Make clear which elements are stretch goals
- [x] Provide a README on how to deploy your system with enough detail that another team could easily follow instructions.
